version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: athenas123
      MYSQL_DATABASE: athenas
      MYSQL_USER: athenas
      MYSQL_PASS: athenas123
    ports:
      - '3306:3306'
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    networks:
      - db-network

  spring_boot_com_mysql:
    build:
      context: ./fontes/AppBack
      dockerfile: ../../Dockerfile
    image: spring_boot_com_mysql/api      
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    depends_on:
      - db
    networks:
      - db-network
    restart: on-failure      
  angular-docker:
    build:
      context: ./fontes/AppFront
      dockerfile: ./Dockerfile
    image: angular-docker/front
    ports:
      - '4200:4200'
    networks:
      - db-network
    restart: on-failure  
    
networks: 
  db-network:
    driver: bridge
