spring:
  application:
    name: appback
    
  datasource:
    url:  jdbc:mysql://localhost:3306/athenas
    username: root
    password: 'athenas123'
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        